/**
 * Email + phone verification service (Phase 4, Step 4.2).
 *
 * Runs an active contact's email through the primary MillionVerifier provider
 * (with optional Bouncer fallback when the primary is unsure), runs its phone
 * through Cognism Diamond, and appends rows to the append-only `verifications`
 * table. Updates the contact's freshness fields (lastVerifiedAt + writeSource
 * + writePriority) at the end.
 *
 * Gate promotion based on verification outcomes is intentionally NOT in scope
 * here — that lives in 4.4. This service is the data-plane producer; downstream
 * services are the consumers.
 *
 * The bulk entry point swallows per-contact errors so a single bad row never
 * stops the batch, and writes one audit_log row summarising the run.
 */

import { randomUUID } from "node:crypto";
import { db } from "@/lib/db";
import {
  bouncer,
  cognismDiamond,
  millionVerifier,
} from "@/providers";

// ============================================================
// Public types
// ============================================================

export type VerificationOptions = {
  /** Default true — fall back from MV to Bouncer if MV returns unknown/<0.5. */
  emailWaterfall?: boolean;
  /** Default false — when true, never call the fallback regardless of waterfall flag. */
  forcePrimaryOnly?: boolean;
  /** Optional grouping id for bulk runs; one is generated by `verifyContactsBulk`. */
  batchId?: string;
  actorUserId: string;
};

export type VerificationOutcome = {
  contactId: string;
  emailVerification?: {
    provider: string;
    status: string;
    confidence: number;
    creditsUsed: number;
  };
  phoneVerification?: {
    provider: string;
    status: string;
    confidence: number;
    creditsUsed: number;
  };
  totalCreditsUsed: number;
  errors: string[];
};

export type BulkVerificationResult = {
  batchId: string;
  total: number;
  succeeded: number;
  failed: number;
  outcomes: VerificationOutcome[];
  creditsByProvider: Record<string, number>;
};

// Constant — see PRD Section 7. The verification flow writes back to the
// contact at priority 100 (mid-tier between intake at ~50 and manual override
// at ~200). Hardcoded for now; tune in 4.4 when promotion logic lands.
const VERIFICATION_WRITE_PRIORITY = 100;

// ============================================================
// Single-contact entry point
// ============================================================

export async function verifyContact(
  contactId: string,
  options: VerificationOptions,
): Promise<VerificationOutcome> {
  const contact = await db.contact.findUnique({
    where: { id: contactId },
    include: { company: { select: { country: true } } },
  });
  if (!contact) {
    throw new Error(`contact ${contactId} not found`);
  }
  if (contact.mergedIntoId !== null) {
    throw new Error(`contact ${contactId} is soft-archived (mergedIntoId set) — cannot verify`);
  }

  const outcome: VerificationOutcome = {
    contactId,
    totalCreditsUsed: 0,
    errors: [],
  };

  // ---- Email verification (with optional waterfall) ----
  if (contact.email) {
    const primary = await millionVerifier.verifyEmail(contact.email);
    let chosen = primary;
    let fallback: Awaited<ReturnType<typeof bouncer.verifyEmail>> | null = null;

    const waterfallEnabled =
      options.emailWaterfall !== false && options.forcePrimaryOnly !== true;

    if (
      waterfallEnabled &&
      primary.status === "unknown" &&
      primary.confidence < 0.5
    ) {
      fallback = await bouncer.verifyEmail(contact.email);
      if (fallback.confidence > chosen.confidence) {
        chosen = fallback;
      }
    }

    // Both attempts are persisted so the audit trail shows every call.
    await db.verification.create({
      data: {
        clientId: contact.clientId,
        contactId,
        verificationType: "email",
        provider: primary.provider,
        status: primary.status,
        confidence: primary.confidence,
        creditsUsed: primary.creditsUsed,
        rawResponse: JSON.stringify(primary.rawResponse),
        batchId: options.batchId ?? null,
      },
    });

    if (fallback) {
      await db.verification.create({
        data: {
          clientId: contact.clientId,
          contactId,
          verificationType: "email",
          provider: fallback.provider,
          status: fallback.status,
          confidence: fallback.confidence,
          creditsUsed: fallback.creditsUsed,
          rawResponse: JSON.stringify(fallback.rawResponse),
          batchId: options.batchId ?? null,
        },
      });
    }

    outcome.emailVerification = {
      provider: chosen.provider,
      status: chosen.status,
      confidence: chosen.confidence,
      creditsUsed: chosen.creditsUsed,
    };
    outcome.totalCreditsUsed +=
      primary.creditsUsed + (fallback?.creditsUsed ?? 0);
  }

  // ---- Phone verification ----
  if (contact.phone) {
    const phoneResult = await cognismDiamond.verifyPhone(
      contact.phone,
      contact.company?.country ?? null,
    );
    await db.verification.create({
      data: {
        clientId: contact.clientId,
        contactId,
        verificationType: "phone",
        provider: phoneResult.provider,
        status: phoneResult.status,
        confidence: phoneResult.confidence,
        creditsUsed: phoneResult.creditsUsed,
        rawResponse: JSON.stringify(phoneResult.rawResponse),
        batchId: options.batchId ?? null,
      },
    });
    outcome.phoneVerification = {
      provider: phoneResult.provider,
      status: phoneResult.status,
      confidence: phoneResult.confidence,
      creditsUsed: phoneResult.creditsUsed,
    };
    outcome.totalCreditsUsed += phoneResult.creditsUsed;
  }

  // ---- Contact freshness update ----
  await db.contact.update({
    where: { id: contactId },
    data: {
      lastVerifiedAt: new Date(),
      writeSource: "verification",
      writePriority: VERIFICATION_WRITE_PRIORITY,
    },
  });

  return outcome;
}

// ============================================================
// Bulk entry point
// ============================================================

export async function verifyContactsBulk(
  contactIds: string[],
  options: VerificationOptions,
): Promise<BulkVerificationResult> {
  const batchId = options.batchId ?? randomUUID();
  const outcomes: VerificationOutcome[] = [];
  let succeeded = 0;
  let failed = 0;
  let firstClientIdSeen: string | null = null;

  for (let i = 0; i < contactIds.length; i++) {
    const id = contactIds[i]!;
    if (i > 0 && i % 500 === 0) {
      console.log(`Checkpoint at ${i}/${contactIds.length}`);
    }
    try {
      const outcome = await verifyContact(id, { ...options, batchId });
      outcomes.push(outcome);
      succeeded += 1;

      if (firstClientIdSeen === null) {
        const c = await db.contact.findUnique({
          where: { id },
          select: { clientId: true },
        });
        firstClientIdSeen = c?.clientId ?? null;
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      outcomes.push({
        contactId: id,
        totalCreditsUsed: 0,
        errors: [message],
      });
      failed += 1;
    }
  }

  // Tally credits from the actual verification rows written under this batch.
  // One group-by is simpler — and accurate — than tracking per-call deltas
  // through the waterfall branches.
  const creditsRows = await db.verification.groupBy({
    by: ["provider"],
    where: { batchId },
    _sum: { creditsUsed: true },
  });
  const creditsByProvider: Record<string, number> = {};
  for (const r of creditsRows) {
    creditsByProvider[r.provider] = r._sum.creditsUsed ?? 0;
  }

  await db.auditLog.create({
    data: {
      clientId: firstClientIdSeen,
      actorUserId: options.actorUserId,
      action: "verification_batch_completed",
      resourceType: "verification_batch",
      resourceId: batchId,
      batchId,
      recordsAffected: succeeded,
      afterState: JSON.stringify({
        total: contactIds.length,
        succeeded,
        failed,
        creditsByProvider,
      }),
    },
  });

  return {
    batchId,
    total: contactIds.length,
    succeeded,
    failed,
    outcomes,
    creditsByProvider,
  };
}
